export const categories = [
  { id: 1, name: "Pizza", image: require("../assets/icons/pizzaIcon.png") },
  { id: 2, name: "Burger", image: require("../assets/icons/pizzaIcon.png") },
  { id: 3, name: "Italian", image: require("../assets/icons/pizzaIcon.png") },
  { id: 4, name: "Chinese", image: require("../assets/icons/pizzaIcon.png") },
  { id: 5, name: "Noodles", image: require("../assets/icons/pizzaIcon.png") },
  { id: 6, name: "Sweets", image: require("../assets/icons/pizzaIcon.png") },
];

export const featured = {
  id: 1,
  title: "Hot and Spicy",
  description: "Soft and tender fries chicken",
  restaurants: [
    {
      id: 1,
      name: "Papa Johns",
      image: require("../assets/images/PizzaStore.jpg"),
      description: "Hot and spicy pizzas",
      lng: -122.4324,
      lat: 37.78825,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/icons/pizzaIcon.png"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/icons/pizzaIcon.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/icons/pizzaIcon.png"),
        },
      ],
    },
    {
      id: 2,
      name: "Papa Johns",
      image: require("../assets/images/PizzaStore.jpg"),
      description: "Hot and spicy pizzas",
      lng: 37.78825,
      lat: -122.4324,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/icons/pizzaIcon.png"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/icons/pizzaIcon.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/icons/pizzaIcon.png"),
        },
      ],
    },
    {
      id: 3,
      name: "Papa Johns",
      image: require("../assets/images/PizzaStore.jpg"),
      description: "Hot and spicy pizzas",
      lng: 37.78825,
      lat: -122.4324,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/icons/pizzaIcon.png"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/icons/pizzaIcon.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/icons/pizzaIcon.png"),
        },
      ],
    },
    {
      id: 4,
      name: "Papa Johns",
      image: require("../assets/images/PizzaStore.jpg"),
      description: "Hot and spicy pizzas",
      lng: 37.78825,
      lat: -122.4324,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/icons/pizzaIcon.png"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/icons/pizzaIcon.png"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/icons/pizzaIcon.png"),
        },
      ],
    },
  ],
};
